from types import SimpleNamespace

from PyQt5 import QtWidgets, QtCore


class ArmorItems:
    # TODO - function based widgets and labels
    # TODO - generalized single armor layout (maybe will add option for adding another items here?)
    # TODO - generalized translation
    # TODO - adding widgets by rows/columns
    def __init__(self, parent, position, size):
        self.root = QtWidgets.QGroupBox(parent)
        self.root.setGeometry(QtCore.QRect(*position, *size))
        self.root.setObjectName("ArmorItems")
        self.armor_1 = SimpleNamespace()
        self.add_armor_1()
        self.add_armor_2()

        self.translate()

    def add_armor_1(self):
        self.armor_1.root = QtWidgets.QGroupBox(self.root)
        self.armor_1.root.setGeometry(QtCore.QRect(10, 30, 591, 131))
        self.armor_1.root.setObjectName("Armor1")
        self.armor_1.container = QtWidgets.QWidget(self.armor_1.root)
        self.armor_1.container.setGeometry(QtCore.QRect(10, 20, 571, 101))
        self.armor_1.container.setObjectName("gridLayoutWidget_15")
        self.armor_1.layout = QtWidgets.QGridLayout(self.armor_1.container)
        self.armor_1.layout.setContentsMargins(9, 9, 9, 9)
        self.armor_1.layout.setSpacing(6)
        self.armor_1.layout.setObjectName("Armor1Layout")
        self.armor_1.test_penalty = QtWidgets.QLineEdit(self.armor_1.container)
        self.armor_1.test_penalty.setMinimumSize(QtCore.QSize(0, 23))
        self.armor_1.test_penalty.setObjectName("armor_1_test_penalty")
        self.armor_1.max_dex_bonus_label = QtWidgets.QLabel(self.armor_1.container)
        self.armor_1.max_dex_bonus_label.setObjectName("armor_1_max_dex_bonus_label")
        self.armor_1.test_penalty_label = QtWidgets.QLabel(self.armor_1.container)
        self.armor_1.test_penalty_label.setObjectName("armor_1_test_penalty_label")
        self.armor_1.type = QtWidgets.QLineEdit(self.armor_1.container)
        self.armor_1.type.setMinimumSize(QtCore.QSize(0, 23))
        self.armor_1.type.setObjectName("armor_1_type")
        self.armor_1.max_dex_bonus = QtWidgets.QLineEdit(self.armor_1.container)
        self.armor_1.max_dex_bonus.setMinimumSize(QtCore.QSize(0, 23))
        self.armor_1.max_dex_bonus.setObjectName("armor_1_max_dex_bonus")
        self.armor_1.name = QtWidgets.QLineEdit(self.armor_1.container)
        self.armor_1.name.setMinimumSize(QtCore.QSize(0, 23))
        self.armor_1.name.setObjectName("armor_1_name")
        self.armor_1.ac_bonus = QtWidgets.QLineEdit(self.armor_1.container)
        self.armor_1.ac_bonus.setMinimumSize(QtCore.QSize(0, 23))
        self.armor_1.ac_bonus.setObjectName("armor_1_ac_bonus")
        self.armor_1.type_label = QtWidgets.QLabel(self.armor_1.container)
        self.armor_1.type_label.setObjectName("armor_1_type_label")
        self.armor_1.ac_bonus_label = QtWidgets.QLabel(self.armor_1.container)
        self.armor_1.ac_bonus_label.setObjectName("armor_1_ac_bonus_label")
        self.armor_1.weight_label = QtWidgets.QLabel(self.armor_1.container)
        self.armor_1.weight_label.setObjectName("armor_1_weight_label")
        self.armor_1.spell_fail_label = QtWidgets.QLabel(self.armor_1.container)
        self.armor_1.spell_fail_label.setObjectName("armor_1_spell_fail_label")
        self.armor_1.speed_label = QtWidgets.QLabel(self.armor_1.container)
        self.armor_1.speed_label.setObjectName("armor_1_speed_label")
        self.armor_1.name_label = QtWidgets.QLabel(self.armor_1.container)
        self.armor_1.name_label.setObjectName("armor_1_name_label")
        self.armor_1.weight = QtWidgets.QLineEdit(self.armor_1.container)
        self.armor_1.weight.setMinimumSize(QtCore.QSize(0, 23))
        self.armor_1.weight.setObjectName("armor_1_weight")
        self.armor_1.spell_fail = QtWidgets.QLineEdit(self.armor_1.container)
        self.armor_1.spell_fail.setMinimumSize(QtCore.QSize(0, 23))
        self.armor_1.spell_fail.setObjectName("armor_1_spell_fail")
        self.armor_1.speed = QtWidgets.QLineEdit(self.armor_1.container)
        self.armor_1.speed.setMinimumSize(QtCore.QSize(0, 23))
        self.armor_1.speed.setObjectName("armor_1_speed")
        self.armor_1.special = QtWidgets.QLineEdit(self.armor_1.container)
        self.armor_1.special.setMinimumSize(QtCore.QSize(0, 23))
        self.armor_1.special.setObjectName("armor_1_special")
        self.armor_1.special_label = QtWidgets.QLabel(self.armor_1.container)
        self.armor_1.special_label.setObjectName("armor_1_special_label")

        self.armor_1.layout.addWidget(self.armor_1.name_label, 0, 0, 1, 1)
        self.armor_1.layout.addWidget(self.armor_1.type_label, 0, 1, 1, 1)
        self.armor_1.layout.addWidget(self.armor_1.ac_bonus_label, 0, 2, 1, 1)
        self.armor_1.layout.addWidget(self.armor_1.test_penalty_label, 0, 3, 1, 1)
        self.armor_1.layout.addWidget(self.armor_1.max_dex_bonus_label, 0, 4, 1, 1)

        self.armor_1.layout.addWidget(self.armor_1.name, 1, 0, 1, 1)
        self.armor_1.layout.addWidget(self.armor_1.type, 1, 1, 1, 1)
        self.armor_1.layout.addWidget(self.armor_1.ac_bonus, 1, 2, 1, 1)
        self.armor_1.layout.addWidget(self.armor_1.test_penalty, 1, 3, 1, 1)
        self.armor_1.layout.addWidget(self.armor_1.max_dex_bonus, 1, 4, 1, 1)

        self.armor_1.layout.addWidget(self.armor_1.special_label, 2, 0, 1, 2)
        self.armor_1.layout.addWidget(self.armor_1.weight_label, 2, 2, 1, 1)
        self.armor_1.layout.addWidget(self.armor_1.spell_fail_label, 2, 3, 1, 1)
        self.armor_1.layout.addWidget(self.armor_1.speed_label, 2, 4, 1, 1)

        self.armor_1.layout.addWidget(self.armor_1.special, 3, 0, 1, 2)
        self.armor_1.layout.addWidget(self.armor_1.weight, 3, 2, 1, 1)
        self.armor_1.layout.addWidget(self.armor_1.spell_fail, 3, 3, 1, 1)
        self.armor_1.layout.addWidget(self.armor_1.speed, 3, 4, 1, 1)

    def add_armor_2(self):
        self.armor_2 = QtWidgets.QGroupBox(self.root)
        self.armor_2.setGeometry(QtCore.QRect(10, 170, 591, 151))
        self.armor_2.setObjectName("Armor2")
        self.container_2 = QtWidgets.QWidget(self.armor_2)
        self.container_2.setGeometry(QtCore.QRect(10, 20, 571, 101))
        self.container_2.setObjectName("gridLayoutWidget_16")
        self.layout_2 = QtWidgets.QGridLayout(self.container_2)
        self.layout_2.setContentsMargins(9, 9, 9, 9)
        self.layout_2.setSpacing(6)
        self.layout_2.setObjectName("Armor2Layout")
        self.armor_2_test_penalty = QtWidgets.QLineEdit(self.container_2)
        self.armor_2_test_penalty.setMinimumSize(QtCore.QSize(0, 23))
        self.armor_2_test_penalty.setObjectName("armor_2_test_penalty")
        self.armor_2_max_dex_bonus_label = QtWidgets.QLabel(self.container_2)
        self.armor_2_max_dex_bonus_label.setObjectName("armor_2_max_dex_bonus_label")
        self.armor_2_test_penalty_label = QtWidgets.QLabel(self.container_2)
        self.armor_2_test_penalty_label.setObjectName("armor_2_test_penalty_label")
        self.armor_2_type = QtWidgets.QLineEdit(self.container_2)
        self.armor_2_type.setMinimumSize(QtCore.QSize(0, 23))
        self.armor_2_type.setObjectName("armor_2_type")
        self.armor_2_max_dex_bonus = QtWidgets.QLineEdit(self.container_2)
        self.armor_2_max_dex_bonus.setMinimumSize(QtCore.QSize(0, 23))
        self.armor_2_max_dex_bonus.setObjectName("armor_2_max_dex_bonus")
        self.armor_2_name = QtWidgets.QLineEdit(self.container_2)
        self.armor_2_name.setMinimumSize(QtCore.QSize(0, 23))
        self.armor_2_name.setObjectName("armor_2_name")
        self.armor_2_ac_bonus = QtWidgets.QLineEdit(self.container_2)
        self.armor_2_ac_bonus.setMinimumSize(QtCore.QSize(0, 23))
        self.armor_2_ac_bonus.setObjectName("armor_2_ac_bonus")
        self.armor_2_type_label = QtWidgets.QLabel(self.container_2)
        self.armor_2_type_label.setObjectName("armor_2_type_label")
        self.armor_2_ac_bonus_label = QtWidgets.QLabel(self.container_2)
        self.armor_2_ac_bonus_label.setObjectName("armor_2_ac_bonus_label")
        self.armor_2_weight_label = QtWidgets.QLabel(self.container_2)
        self.armor_2_weight_label.setObjectName("armor_2_weight_label")
        self.armor_2_spell_fail_label = QtWidgets.QLabel(self.container_2)
        self.armor_2_spell_fail_label.setObjectName("armor_2_spell_fail_label")
        self.armor_2_speed_label = QtWidgets.QLabel(self.container_2)
        self.armor_2_speed_label.setObjectName("armor_2_speed_label")
        self.armor_2_name_label = QtWidgets.QLabel(self.container_2)
        self.armor_2_name_label.setObjectName("armor_2_name_label")
        self.armor_2_weight = QtWidgets.QLineEdit(self.container_2)
        self.armor_2_weight.setMinimumSize(QtCore.QSize(0, 23))
        self.armor_2_weight.setObjectName("armor_2_weight")
        self.armor_2_spell_fail = QtWidgets.QLineEdit(self.container_2)
        self.armor_2_spell_fail.setMinimumSize(QtCore.QSize(0, 23))
        self.armor_2_spell_fail.setObjectName("armor_2_spell_fail")
        self.armor_2_speed = QtWidgets.QLineEdit(self.container_2)
        self.armor_2_speed.setMinimumSize(QtCore.QSize(0, 23))
        self.armor_2_speed.setObjectName("armor_2_speed")
        self.armor_2_special = QtWidgets.QLineEdit(self.container_2)
        self.armor_2_special.setMinimumSize(QtCore.QSize(0, 23))
        self.armor_2_special.setObjectName("armor_2_special")
        self.armor_2_special_label = QtWidgets.QLabel(self.container_2)
        self.armor_2_special_label.setObjectName("armor_2_special_label")
        self.layout_2.addWidget(self.armor_2_test_penalty, 1, 3, 1, 1)
        self.layout_2.addWidget(self.armor_2_max_dex_bonus_label, 0, 4, 1, 1)
        self.layout_2.addWidget(self.armor_2_test_penalty_label, 0, 3, 1, 1)
        self.layout_2.addWidget(self.armor_2_type, 1, 1, 1, 1)
        self.layout_2.addWidget(self.armor_2_max_dex_bonus, 1, 4, 1, 1)
        self.layout_2.addWidget(self.armor_2_name, 1, 0, 1, 1)
        self.layout_2.addWidget(self.armor_2_ac_bonus, 1, 2, 1, 1)
        self.layout_2.addWidget(self.armor_2_type_label, 0, 1, 1, 1)
        self.layout_2.addWidget(self.armor_2_ac_bonus_label, 0, 2, 1, 1)
        self.layout_2.addWidget(self.armor_2_weight_label, 2, 2, 1, 1)
        self.layout_2.addWidget(self.armor_2_spell_fail_label, 2, 3, 1, 1)
        self.layout_2.addWidget(self.armor_2_speed_label, 2, 4, 1, 1)
        self.layout_2.addWidget(self.armor_2_name_label, 0, 0, 1, 1)
        self.layout_2.addWidget(self.armor_2_weight, 3, 2, 1, 1)
        self.layout_2.addWidget(self.armor_2_spell_fail, 3, 3, 1, 1)
        self.layout_2.addWidget(self.armor_2_speed, 3, 4, 1, 1)
        self.layout_2.addWidget(self.armor_2_special, 3, 0, 1, 2)
        self.layout_2.addWidget(self.armor_2_special_label, 2, 0, 1, 2)

    def translate(self):
        _translate = QtCore.QCoreApplication.translate
        self.root.setTitle(_translate("MainWindow", "Armor items"))

        self.armor_1.root.setTitle(_translate("MainWindow", "Armor / Protective item"))
        self.armor_1.test_penalty.setText(_translate("MainWindow", "10"))
        self.armor_1.max_dex_bonus_label.setText(_translate("MainWindow", "Max dex. bonus"))
        self.armor_1.test_penalty_label.setText(_translate("MainWindow", "Tests penalty"))
        self.armor_1.type.setText(_translate("MainWindow", "Lorem ipsum"))
        self.armor_1.max_dex_bonus.setText(_translate("MainWindow", "10"))
        self.armor_1.name.setText(_translate("MainWindow", "Lorem ipsum"))
        self.armor_1.ac_bonus.setText(_translate("MainWindow", "10"))
        self.armor_1.type_label.setText(_translate("MainWindow", "Type"))
        self.armor_1.ac_bonus_label.setText(_translate("MainWindow", "AC bonus"))
        self.armor_1.weight_label.setText(_translate("MainWindow", "Weight"))
        self.armor_1.spell_fail_label.setText(_translate("MainWindow", "Spell fail"))
        self.armor_1.speed_label.setText(_translate("MainWindow", "Speed"))
        self.armor_1.name_label.setText(_translate("MainWindow", "Name"))
        self.armor_1.weight.setText(_translate("MainWindow", "10"))
        self.armor_1.spell_fail.setText(_translate("MainWindow", "10"))
        self.armor_1.speed.setText(_translate("MainWindow", "10"))
        self.armor_1.special.setText(_translate("MainWindow", "Lorem ipsum"))
        self.armor_1.special_label.setText(_translate("MainWindow", "Special"))

        self.armor_2.setTitle(_translate("MainWindow", "Shield / Protective item"))
        self.armor_2_test_penalty.setText(_translate("MainWindow", "10"))
        self.armor_2_max_dex_bonus_label.setText(_translate("MainWindow", "Max dex. bonus"))
        self.armor_2_test_penalty_label.setText(_translate("MainWindow", "Tests penalty"))
        self.armor_2_type.setText(_translate("MainWindow", "Lorem ipsum"))
        self.armor_2_max_dex_bonus.setText(_translate("MainWindow", "10"))
        self.armor_2_name.setText(_translate("MainWindow", "Lorem ipsum"))
        self.armor_2_ac_bonus.setText(_translate("MainWindow", "10"))
        self.armor_2_type_label.setText(_translate("MainWindow", "Type"))
        self.armor_2_ac_bonus_label.setText(_translate("MainWindow", "AC bonus"))
        self.armor_2_weight_label.setText(_translate("MainWindow", "Weight"))
        self.armor_2_spell_fail_label.setText(_translate("MainWindow", "Spell fail"))
        self.armor_2_speed_label.setText(_translate("MainWindow", "Speed"))
        self.armor_2_name_label.setText(_translate("MainWindow", "Name"))
        self.armor_2_weight.setText(_translate("MainWindow", "10"))
        self.armor_2_spell_fail.setText(_translate("MainWindow", "10"))
        self.armor_2_speed.setText(_translate("MainWindow", "10"))
        self.armor_2_special.setText(_translate("MainWindow", "Lorem ipsum"))
        self.armor_2_special_label.setText(_translate("MainWindow", "Special"))
