from PyQt5 import QtWidgets, QtCore


class AttributesBox:
    def __init__(self, centralwidget):
        self.root = QtWidgets.QGroupBox(centralwidget)
        self.root.setGeometry(QtCore.QRect(10, 200, 311, 231))
        self.root.setObjectName("AttributesBox")
        self.container = QtWidgets.QWidget(self.root)
        self.container.setGeometry(QtCore.QRect(20, 20, 285, 201))
        self.container.setObjectName("gridLayoutWidget")
        self.layout = QtWidgets.QGridLayout(self.container)
        self.layout.setContentsMargins(9, 9, 9, 9)
        self.layout.setSpacing(6)
        self.layout.setObjectName("AttributesLayout")
        self.attr_str_val = QtWidgets.QLineEdit(self.container)
        self.attr_str_val.setMinimumSize(QtCore.QSize(0, 23))
        self.attr_str_val.setObjectName("attr_str_val")
        self.attr_head_name = QtWidgets.QLabel(self.container)
        self.attr_head_name.setMinimumSize(QtCore.QSize(0, 0))
        self.attr_head_name.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.attr_head_name.setBaseSize(QtCore.QSize(10, 0))
        self.attr_head_name.setAlignment(QtCore.Qt.AlignCenter)
        self.attr_head_name.setObjectName("attr_head_name")
        self.attr_int_label = QtWidgets.QLabel(self.container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr_int_label.sizePolicy().hasHeightForWidth())
        self.attr_int_label.setSizePolicy(sizePolicy)
        self.attr_int_label.setMinimumSize(QtCore.QSize(40, 0))
        self.attr_int_label.setBaseSize(QtCore.QSize(10, 0))
        self.attr_int_label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.attr_int_label.setObjectName("attr_int_label")
        self.attr_con_mod = QtWidgets.QLineEdit(self.container)
        self.attr_con_mod.setMinimumSize(QtCore.QSize(0, 23))
        self.attr_con_mod.setObjectName("attr_con_mod")
        self.Attr_head_mod = QtWidgets.QLabel(self.container)
        self.Attr_head_mod.setAlignment(QtCore.Qt.AlignCenter)
        self.Attr_head_mod.setObjectName("Attr_head_mod")
        self.attr_dex_val = QtWidgets.QLineEdit(self.container)
        self.attr_dex_val.setMinimumSize(QtCore.QSize(0, 23))
        self.attr_dex_val.setObjectName("attr_dex_val")
        self.attr_head_temp_mod = QtWidgets.QLabel(self.container)
        self.attr_head_temp_mod.setMinimumSize(QtCore.QSize(0, 20))
        self.attr_head_temp_mod.setMaximumSize(QtCore.QSize(16777215, 20))
        self.attr_head_temp_mod.setAlignment(QtCore.Qt.AlignCenter)
        self.attr_head_temp_mod.setWordWrap(True)
        self.attr_head_temp_mod.setObjectName("attr_head_temp_mod")
        self.attr_dex_label = QtWidgets.QLabel(self.container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr_dex_label.sizePolicy().hasHeightForWidth())
        self.attr_dex_label.setSizePolicy(sizePolicy)
        self.attr_dex_label.setMinimumSize(QtCore.QSize(40, 0))
        self.attr_dex_label.setBaseSize(QtCore.QSize(10, 0))
        self.attr_dex_label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.attr_dex_label.setObjectName("attr_dex_label")
        self.attr_head_temp_val = QtWidgets.QLabel(self.container)
        self.attr_head_temp_val.setAlignment(QtCore.Qt.AlignCenter)
        self.attr_head_temp_val.setObjectName("attr_head_temp_val")
        self.attr_con_temp_mod = QtWidgets.QLineEdit(self.container)
        self.attr_con_temp_mod.setMinimumSize(QtCore.QSize(0, 23))
        self.attr_con_temp_mod.setObjectName("attr_con_temp_mod")
        self.attr_int_temp_mod = QtWidgets.QLineEdit(self.container)
        self.attr_int_temp_mod.setMinimumSize(QtCore.QSize(0, 23))
        self.attr_int_temp_mod.setObjectName("attr_int_temp_mod")
        self.attr_con_val = QtWidgets.QLineEdit(self.container)
        self.attr_con_val.setMinimumSize(QtCore.QSize(0, 23))
        self.attr_con_val.setObjectName("attr_con_val")
        self.attr_con_temp_val = QtWidgets.QLineEdit(self.container)
        self.attr_con_temp_val.setMinimumSize(QtCore.QSize(0, 23))
        self.attr_con_temp_val.setObjectName("attr_con_temp_val")
        self.attr_wis_mod = QtWidgets.QLineEdit(self.container)
        self.attr_wis_mod.setMinimumSize(QtCore.QSize(0, 23))
        self.attr_wis_mod.setObjectName("attr_wis_mod")
        self.attr_wis_temp_mod = QtWidgets.QLineEdit(self.container)
        self.attr_wis_temp_mod.setMinimumSize(QtCore.QSize(0, 23))
        self.attr_wis_temp_mod.setObjectName("attr_wis_temp_mod")
        self.attr_wis_temp_val = QtWidgets.QLineEdit(self.container)
        self.attr_wis_temp_val.setMinimumSize(QtCore.QSize(0, 23))
        self.attr_wis_temp_val.setObjectName("attr_wis_temp_val")
        self.attr_dex_mod = QtWidgets.QLineEdit(self.container)
        self.attr_dex_mod.setMinimumSize(QtCore.QSize(0, 23))
        self.attr_dex_mod.setObjectName("attr_dex_mod")
        self.attr_dex_temp_val = QtWidgets.QLineEdit(self.container)
        self.attr_dex_temp_val.setMinimumSize(QtCore.QSize(0, 23))
        self.attr_dex_temp_val.setObjectName("attr_dex_temp_val")
        self.attr_con_label = QtWidgets.QLabel(self.container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr_con_label.sizePolicy().hasHeightForWidth())
        self.attr_con_label.setSizePolicy(sizePolicy)
        self.attr_con_label.setMinimumSize(QtCore.QSize(40, 0))
        self.attr_con_label.setBaseSize(QtCore.QSize(10, 0))
        self.attr_con_label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.attr_con_label.setObjectName("attr_con_label")
        self.attr_dex_temp_mod = QtWidgets.QLineEdit(self.container)
        self.attr_dex_temp_mod.setMinimumSize(QtCore.QSize(0, 23))
        self.attr_dex_temp_mod.setObjectName("attr_dex_temp_mod")
        self.attr_wis_val = QtWidgets.QLineEdit(self.container)
        self.attr_wis_val.setMinimumSize(QtCore.QSize(0, 23))
        self.attr_wis_val.setObjectName("attr_wis_val")
        self.attr_head_val = QtWidgets.QLabel(self.container)
        self.attr_head_val.setAlignment(QtCore.Qt.AlignCenter)
        self.attr_head_val.setObjectName("attr_head_val")
        self.attr_int_temp_val = QtWidgets.QLineEdit(self.container)
        self.attr_int_temp_val.setMinimumSize(QtCore.QSize(0, 23))
        self.attr_int_temp_val.setObjectName("attr_int_temp_val")
        self.attr_int_mod = QtWidgets.QLineEdit(self.container)
        self.attr_int_mod.setMinimumSize(QtCore.QSize(0, 23))
        self.attr_int_mod.setObjectName("attr_int_mod")
        self.attr_int_val = QtWidgets.QLineEdit(self.container)
        self.attr_int_val.setMinimumSize(QtCore.QSize(0, 23))
        self.attr_int_val.setObjectName("attr_int_val")
        self.attr_wis_label = QtWidgets.QLabel(self.container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr_wis_label.sizePolicy().hasHeightForWidth())
        self.attr_wis_label.setSizePolicy(sizePolicy)
        self.attr_wis_label.setMinimumSize(QtCore.QSize(40, 0))
        self.attr_wis_label.setBaseSize(QtCore.QSize(10, 0))
        self.attr_wis_label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.attr_wis_label.setObjectName("attr_wis_label")
        self.attr_str_temp_mod = QtWidgets.QLineEdit(self.container)
        self.attr_str_temp_mod.setObjectName("attr_str_temp_mod")
        self.layout.addWidget(self.attr_str_temp_mod, 1, 4, 1, 1)
        self.attr_str_label = QtWidgets.QLabel(self.container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr_str_label.sizePolicy().hasHeightForWidth())
        self.attr_str_label.setSizePolicy(sizePolicy)
        self.attr_str_label.setMinimumSize(QtCore.QSize(40, 0))
        self.attr_str_label.setBaseSize(QtCore.QSize(10, 0))
        self.attr_str_label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.attr_str_label.setObjectName("attr_str_label")
        self.attr_str_mod = QtWidgets.QLineEdit(self.container)
        self.attr_str_mod.setMinimumSize(QtCore.QSize(0, 23))
        self.attr_str_mod.setObjectName("attr_str_mod")
        self.attr_str_temp_val = QtWidgets.QLineEdit(self.container)
        self.attr_str_temp_val.setMinimumSize(QtCore.QSize(0, 23))
        self.attr_str_temp_val.setObjectName("attr_str_temp_val")
        self.attr_cha_label = QtWidgets.QLabel(self.container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attr_cha_label.sizePolicy().hasHeightForWidth())
        self.attr_cha_label.setSizePolicy(sizePolicy)
        self.attr_cha_label.setMinimumSize(QtCore.QSize(40, 0))
        self.attr_cha_label.setBaseSize(QtCore.QSize(10, 0))
        self.attr_cha_label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.attr_cha_label.setObjectName("attr_cha_label")
        self.attr_cha_val = QtWidgets.QLineEdit(self.container)
        self.attr_cha_val.setMinimumSize(QtCore.QSize(0, 23))
        self.attr_cha_val.setObjectName("attr_cha_val")
        self.attr_cha_mod = QtWidgets.QLineEdit(self.container)
        self.attr_cha_mod.setMinimumSize(QtCore.QSize(0, 23))
        self.attr_cha_mod.setObjectName("attr_cha_mod")
        self.attr_cha_temp_val = QtWidgets.QLineEdit(self.container)
        self.attr_cha_temp_val.setMinimumSize(QtCore.QSize(0, 23))
        self.attr_cha_temp_val.setObjectName("attr_cha_temp_val")
        self.attr_cha_temp_mod = QtWidgets.QLineEdit(self.container)
        self.attr_cha_temp_mod.setMinimumSize(QtCore.QSize(0, 23))
        self.attr_cha_temp_mod.setObjectName("attr_cha_temp_mod")

        self.layout.addWidget(self.attr_str_val, 1, 1, 1, 1)
        self.layout.addWidget(self.attr_head_name, 0, 0, 1, 1)
        self.layout.addWidget(self.attr_int_label, 4, 0, 1, 1)
        self.layout.addWidget(self.attr_con_mod, 3, 2, 1, 1)
        self.layout.addWidget(self.Attr_head_mod, 0, 2, 1, 1)
        self.layout.addWidget(self.attr_dex_val, 2, 1, 1, 1)
        self.layout.addWidget(self.attr_head_temp_mod, 0, 4, 1, 1)
        self.layout.addWidget(self.attr_dex_label, 2, 0, 1, 1)
        self.layout.addWidget(self.attr_head_temp_val, 0, 3, 1, 1)
        self.layout.addWidget(self.attr_con_temp_mod, 3, 4, 1, 1)
        self.layout.addWidget(self.attr_int_temp_mod, 4, 4, 1, 1)
        self.layout.addWidget(self.attr_con_val, 3, 1, 1, 1)
        self.layout.addWidget(self.attr_con_temp_val, 3, 3, 1, 1)
        self.layout.addWidget(self.attr_wis_mod, 5, 2, 1, 1)
        self.layout.addWidget(self.attr_wis_temp_mod, 5, 4, 1, 1)
        self.layout.addWidget(self.attr_wis_temp_val, 5, 3, 1, 1)
        self.layout.addWidget(self.attr_dex_mod, 2, 2, 1, 1)
        self.layout.addWidget(self.attr_dex_temp_val, 2, 3, 1, 1)
        self.layout.addWidget(self.attr_con_label, 3, 0, 1, 1)
        self.layout.addWidget(self.attr_dex_temp_mod, 2, 4, 1, 1)
        self.layout.addWidget(self.attr_wis_val, 5, 1, 1, 1)
        self.layout.addWidget(self.attr_head_val, 0, 1, 1, 1)
        self.layout.addWidget(self.attr_int_temp_val, 4, 3, 1, 1)
        self.layout.addWidget(self.attr_int_mod, 4, 2, 1, 1)
        self.layout.addWidget(self.attr_int_val, 4, 1, 1, 1)
        self.layout.addWidget(self.attr_wis_label, 5, 0, 1, 1)
        self.layout.addWidget(self.attr_str_label, 1, 0, 1, 1)
        self.layout.addWidget(self.attr_str_mod, 1, 2, 1, 1)
        self.layout.addWidget(self.attr_str_temp_val, 1, 3, 1, 1)
        self.layout.addWidget(self.attr_cha_label, 6, 0, 1, 1)
        self.layout.addWidget(self.attr_cha_val, 6, 1, 1, 1)
        self.layout.addWidget(self.attr_cha_mod, 6, 2, 1, 1)
        self.layout.addWidget(self.attr_cha_temp_val, 6, 3, 1, 1)
        self.layout.addWidget(self.attr_cha_temp_mod, 6, 4, 1, 1)
        self.translate_attributes_box()

    def translate_attributes_box(self):
        _translate = QtCore.QCoreApplication.translate
        self.root.setTitle(_translate("MainWindow", "Attributes"))
        self.attr_str_val.setText(_translate("MainWindow", "10"))
        self.attr_head_name.setText(_translate("MainWindow", "Atrribute"))
        self.attr_int_label.setText(_translate("MainWindow", "INT"))
        self.attr_con_mod.setText(_translate("MainWindow", "10"))
        self.Attr_head_mod.setText(_translate("MainWindow", "Mod"))
        self.attr_dex_val.setText(_translate("MainWindow", "10"))
        self.attr_head_temp_mod.setText(_translate("MainWindow", "Temp mod"))
        self.attr_dex_label.setText(_translate("MainWindow", "DEX"))
        self.attr_head_temp_val.setText(_translate("MainWindow", "Temp val"))
        self.attr_con_temp_mod.setText(_translate("MainWindow", "10"))
        self.attr_int_temp_mod.setText(_translate("MainWindow", "10"))
        self.attr_con_val.setText(_translate("MainWindow", "10"))
        self.attr_con_temp_val.setText(_translate("MainWindow", "10"))
        self.attr_wis_mod.setText(_translate("MainWindow", "10"))
        self.attr_wis_temp_mod.setText(_translate("MainWindow", "10"))
        self.attr_wis_temp_val.setText(_translate("MainWindow", "10"))
        self.attr_dex_mod.setText(_translate("MainWindow", "10"))
        self.attr_dex_temp_val.setText(_translate("MainWindow", "10"))
        self.attr_con_label.setText(_translate("MainWindow", "CON"))
        self.attr_dex_temp_mod.setText(_translate("MainWindow", "10"))
        self.attr_wis_val.setText(_translate("MainWindow", "10"))
        self.attr_head_val.setText(_translate("MainWindow", "Value"))
        self.attr_int_temp_val.setText(_translate("MainWindow", "10"))
        self.attr_int_mod.setText(_translate("MainWindow", "10"))
        self.attr_int_val.setText(_translate("MainWindow", "10"))
        self.attr_wis_label.setText(_translate("MainWindow", "WIS"))
        self.attr_str_temp_mod.setText(_translate("MainWindow", "10"))
        self.attr_str_label.setText(_translate("MainWindow", "STR"))
        self.attr_str_mod.setText(_translate("MainWindow", "10"))
        self.attr_str_temp_val.setText(_translate("MainWindow", "10"))
        self.attr_cha_label.setText(_translate("MainWindow", "CHA"))
        self.attr_cha_val.setText(_translate("MainWindow", "10"))
        self.attr_cha_mod.setText(_translate("MainWindow", "10"))
        self.attr_cha_temp_val.setText(_translate("MainWindow", "10"))
        self.attr_cha_temp_mod.setText(_translate("MainWindow", "10"))
