from PyQt5 import QtWidgets, QtCore, QtGui


class BasicInfoBox:
    def __init__(self, centralwidget):
        self.root = QtWidgets.QGroupBox(centralwidget)
        palette = self.create_palette()
        self.root.setGeometry(QtCore.QRect(10, 0, 811, 201))
        self.root.setObjectName("BasicInfoBox")
        self.container = QtWidgets.QWidget(self.root)
        self.container.setGeometry(QtCore.QRect(10, 20, 791, 162))
        self.container.setObjectName("gridLayoutWidget_2")
        self.layout = QtWidgets.QGridLayout(self.container)
        self.layout.setContentsMargins(9, 9, 9, 9)
        self.layout.setSpacing(6)
        self.layout.setObjectName("BasicInfoLayout")
        self.character_class_label = QtWidgets.QLabel(self.container)
        self.character_class_label.setMinimumSize(QtCore.QSize(178, 16))
        self.character_class_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.character_class_label.setIndent(-1)
        self.character_class_label.setObjectName("character_class_label")
        self.character_faith_label = QtWidgets.QLabel(self.container)
        self.character_faith_label.setMinimumSize(QtCore.QSize(178, 16))
        self.character_faith_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.character_faith_label.setIndent(-1)
        self.character_faith_label.setObjectName("character_faith_label")
        self.character_race_label = QtWidgets.QLabel(self.container)
        self.character_race_label.setMinimumSize(QtCore.QSize(177, 16))
        self.character_race_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.character_race_label.setIndent(-1)
        self.character_race_label.setObjectName("character_race_label")
        self.character_alignement_label = QtWidgets.QLabel(self.container)
        self.character_alignement_label.setMinimumSize(QtCore.QSize(178, 16))
        self.character_alignement_label.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.character_alignement_label.setIndent(-1)
        self.character_alignement_label.setObjectName("character_alignement_label")
        self.character_race = QtWidgets.QLineEdit(self.container)
        self.character_race.setMinimumSize(QtCore.QSize(177, 23))
        self.character_race.setPalette(palette)
        self.character_race.setAlignment(QtCore.Qt.AlignCenter)
        self.character_race.setObjectName("character_race")
        self.character_alignement = QtWidgets.QLineEdit(self.container)
        self.character_alignement.setMinimumSize(QtCore.QSize(178, 23))
        self.character_alignement.setPalette(palette)
        self.character_alignement.setAlignment(QtCore.Qt.AlignCenter)
        self.character_alignement.setObjectName("character_alignement")
        self.character_class = QtWidgets.QLineEdit(self.container)
        self.character_class.setMinimumSize(QtCore.QSize(178, 23))
        self.character_class.setPalette(palette)
        self.character_class.setAlignment(QtCore.Qt.AlignCenter)
        self.character_class.setObjectName("character_class")
        self.character_faith = QtWidgets.QLineEdit(self.container)
        self.character_faith.setMinimumSize(QtCore.QSize(178, 23))
        self.character_faith.setPalette(palette)
        self.character_faith.setAlignment(QtCore.Qt.AlignCenter)
        self.character_faith.setObjectName("character_faith")
        self.character_name_label = QtWidgets.QLabel(self.container)
        self.character_name_label.setIndent(-1)
        self.character_name_label.setObjectName("character_name_label")
        self.character_name = QtWidgets.QLineEdit(self.container)
        self.character_name.setMinimumSize(QtCore.QSize(0, 23))
        self.character_name.setPalette(palette)
        self.character_name.setObjectName("character_name")
        self.player_name_label = QtWidgets.QLabel(self.container)
        self.player_name_label.setIndent(-1)
        self.player_name_label.setObjectName("player_name_label")
        self.character_height_label = QtWidgets.QLabel(self.container)
        self.character_height_label.setMinimumSize(QtCore.QSize(86, 15))
        self.character_height_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.character_height_label.setIndent(-1)
        self.character_height_label.setObjectName("character_height_label")
        self.character_height = QtWidgets.QLineEdit(self.container)
        self.character_height.setMinimumSize(QtCore.QSize(86, 23))
        self.character_height.setPalette(palette)
        self.character_height.setAlignment(QtCore.Qt.AlignCenter)
        self.character_height.setObjectName("character_height")
        self.character_weight_label = QtWidgets.QLabel(self.container)
        self.character_weight_label.setMinimumSize(QtCore.QSize(86, 15))
        self.character_weight_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.character_weight_label.setIndent(-1)
        self.character_weight_label.setObjectName("character_weight_label")
        self.character_weight = QtWidgets.QLineEdit(self.container)
        self.character_weight.setMinimumSize(QtCore.QSize(86, 23))
        self.character_weight.setPalette(palette)
        self.character_weight.setAlignment(QtCore.Qt.AlignCenter)
        self.character_weight.setObjectName("character_weight")
        self.character_eyes_label = QtWidgets.QLabel(self.container)
        self.character_eyes_label.setMinimumSize(QtCore.QSize(86, 15))
        self.character_eyes_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.character_eyes_label.setIndent(-1)
        self.character_eyes_label.setObjectName("character_eyes_label")
        self.character_hair = QtWidgets.QLineEdit(self.container)
        self.character_hair.setMinimumSize(QtCore.QSize(86, 23))
        self.character_hair.setPalette(palette)
        self.character_hair.setAlignment(QtCore.Qt.AlignCenter)
        self.character_hair.setObjectName("character_hair")
        self.player_name = QtWidgets.QLineEdit(self.container)
        self.player_name.setMinimumSize(QtCore.QSize(0, 23))
        self.player_name.setPalette(palette)
        self.player_name.setObjectName("player_name")
        self.character_eyes = QtWidgets.QLineEdit(self.container)
        self.character_eyes.setMinimumSize(QtCore.QSize(86, 23))
        self.character_eyes.setPalette(palette)
        self.character_eyes.setAlignment(QtCore.Qt.AlignCenter)
        self.character_eyes.setObjectName("character_eyes")
        self.character_hair_label = QtWidgets.QLabel(self.container)
        self.character_hair_label.setMinimumSize(QtCore.QSize(86, 15))
        self.character_hair_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.character_hair_label.setIndent(-1)
        self.character_hair_label.setObjectName("character_hair_label")
        self.character_gender = QtWidgets.QLineEdit(self.container)
        self.character_gender.setMinimumSize(QtCore.QSize(85, 23))
        self.character_gender.setPalette(palette)
        self.character_gender.setAlignment(QtCore.Qt.AlignCenter)
        self.character_gender.setObjectName("character_gender")
        self.character_age = QtWidgets.QLineEdit(self.container)
        self.character_age.setMinimumSize(QtCore.QSize(86, 23))
        self.character_age.setPalette(palette)
        self.character_age.setAlignment(QtCore.Qt.AlignCenter)
        self.character_age.setObjectName("character_age")
        self.character_size_label = QtWidgets.QLabel(self.container)
        self.character_size_label.setMinimumSize(QtCore.QSize(86, 15))
        self.character_size_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.character_size_label.setIndent(-1)
        self.character_size_label.setObjectName("character_size_label")
        self.character_size = QtWidgets.QLineEdit(self.container)
        self.character_size.setMinimumSize(QtCore.QSize(86, 23))
        self.character_size.setPalette(palette)
        self.character_size.setAlignment(QtCore.Qt.AlignCenter)
        self.character_size.setObjectName("character_size")
        self.character_age_label = QtWidgets.QLabel(self.container)
        self.character_age_label.setMinimumSize(QtCore.QSize(86, 15))
        self.character_age_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.character_age_label.setIndent(-1)
        self.character_age_label.setObjectName("character_age_label")
        self.character_gender_label = QtWidgets.QLabel(self.container)
        self.character_gender_label.setMinimumSize(QtCore.QSize(85, 15))
        self.character_gender_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.character_gender_label.setIndent(-1)
        self.character_gender_label.setObjectName("character_gender_label")
        self.character_level = QtWidgets.QLineEdit(self.container)
        self.character_level.setMinimumSize(QtCore.QSize(86, 23))
        self.character_level.setPalette(palette)
        self.character_level.setAlignment(QtCore.Qt.AlignCenter)
        self.character_level.setObjectName("character_level")
        self.character_level_label = QtWidgets.QLabel(self.container)
        self.character_level_label.setMinimumSize(QtCore.QSize(86, 15))
        self.character_level_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.character_level_label.setIndent(-1)
        self.character_level_label.setObjectName("character_level_label")

        self.layout.addWidget(self.character_class_label, 2, 0, 1, 2)
        self.layout.addWidget(self.character_faith_label, 2, 6, 1, 2)
        self.layout.addWidget(self.character_race_label, 2, 2, 1, 2)
        self.layout.addWidget(self.character_alignement_label, 2, 4, 1, 2)
        self.layout.addWidget(self.character_race, 3, 2, 1, 2)
        self.layout.addWidget(self.character_alignement, 3, 4, 1, 2)
        self.layout.addWidget(self.character_class, 3, 0, 1, 2)
        self.layout.addWidget(self.character_faith, 3, 6, 1, 2)
        self.layout.addWidget(self.character_name_label, 0, 0, 1, 4)
        self.layout.addWidget(self.character_name, 1, 0, 1, 4)
        self.layout.addWidget(self.player_name_label, 0, 4, 1, 4)
        self.layout.addWidget(self.character_height_label, 4, 4, 1, 1)
        self.layout.addWidget(self.character_height, 5, 4, 1, 1)
        self.layout.addWidget(self.character_weight_label, 4, 5, 1, 1)
        self.layout.addWidget(self.character_weight, 5, 5, 1, 1)
        self.layout.addWidget(self.character_eyes_label, 4, 6, 1, 1)
        self.layout.addWidget(self.character_hair, 5, 7, 1, 1)
        self.layout.addWidget(self.player_name, 1, 4, 1, 4)
        self.layout.addWidget(self.character_eyes, 5, 6, 1, 1)
        self.layout.addWidget(self.character_hair_label, 4, 7, 1, 1)
        self.layout.addWidget(self.character_gender, 5, 3, 1, 1)
        self.layout.addWidget(self.character_age, 5, 2, 1, 1)
        self.layout.addWidget(self.character_size_label, 4, 1, 1, 1)
        self.layout.addWidget(self.character_size, 5, 1, 1, 1)
        self.layout.addWidget(self.character_age_label, 4, 2, 1, 1)
        self.layout.addWidget(self.character_gender_label, 4, 3, 1, 1)
        self.layout.addWidget(self.character_level, 5, 0, 1, 1)
        self.layout.addWidget(self.character_level_label, 4, 0, 1, 1)

        self.translate_basic_info_box()

    def translate_basic_info_box(self):
        _translate = QtCore.QCoreApplication.translate
        self.root.setTitle(_translate("MainWindow", "Basic Info"))
        self.character_class_label.setText(_translate("MainWindow", "Class"))
        self.character_faith_label.setText(_translate("MainWindow", "Faith"))
        self.character_race_label.setText(_translate("MainWindow", "Race"))
        self.character_alignement_label.setText(_translate("MainWindow", "Alignement"))
        self.character_race.setText(_translate("MainWindow", "Lorem ipsum"))
        self.character_alignement.setText(_translate("MainWindow", "Lorem ipsum"))
        self.character_class.setText(_translate("MainWindow", "Lorem ipsum"))
        self.character_faith.setText(_translate("MainWindow", "Lorem ipsum"))
        self.character_name_label.setText(_translate("MainWindow", "Character name"))
        self.character_name.setText(_translate("MainWindow", "Lorem ipsum"))
        self.player_name_label.setText(_translate("MainWindow", "Player name"))
        self.character_height_label.setText(_translate("MainWindow", "Height"))
        self.character_height.setText(_translate("MainWindow", "10"))
        self.character_weight_label.setText(_translate("MainWindow", "Weight"))
        self.character_weight.setText(_translate("MainWindow", "10"))
        self.character_eyes_label.setText(_translate("MainWindow", "Eyes"))
        self.character_hair.setText(_translate("MainWindow", "Lorem ipsum"))
        self.player_name.setText(_translate("MainWindow", "Lorem ipsum"))
        self.character_eyes.setText(_translate("MainWindow", "Lorem ipsum"))
        self.character_hair_label.setText(_translate("MainWindow", "Hair"))
        self.character_gender.setText(_translate("MainWindow", "Lorem ipsum"))
        self.character_age.setText(_translate("MainWindow", "10"))
        self.character_size_label.setText(_translate("MainWindow", "Size"))
        self.character_size.setText(_translate("MainWindow", "Lorem ipsum"))
        self.character_age_label.setText(_translate("MainWindow", "Age"))
        self.character_gender_label.setText(_translate("MainWindow", "Gender"))
        self.character_level.setText(_translate("MainWindow", "10"))
        self.character_level_label.setText(_translate("MainWindow", "Level"))

    def create_palette(self):
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        return palette
