from PyQt5 import QtWidgets, QtCore


class SkillsBox:
    def __init__(self, centralwidget):
        self.SkillsBox = QtWidgets.QGroupBox(centralwidget)
        self.SkillsBox.setGeometry(QtCore.QRect(840, 290, 581, 191))
        self.SkillsBox.setMinimumSize(QtCore.QSize(571, 91))
        self.SkillsBox.setObjectName("SkillsBox")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.SkillsBox)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 561, 61))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.SkillsLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.SkillsLayout.setContentsMargins(9, 9, 9, 9)
        self.SkillsLayout.setSpacing(6)
        self.SkillsLayout.setObjectName("SkillsLayout")
        self.skills_description_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.skills_description_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.skills_description_label.setAlignment(QtCore.Qt.AlignCenter)
        self.skills_description_label.setObjectName("skills_description_label")
        self.skills_1_description_button = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.skills_1_description_button.setObjectName("skills_1_description_button")
        self.skills_1_misc_mod = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.skills_1_misc_mod.setMinimumSize(QtCore.QSize(0, 23))
        self.skills_1_misc_mod.setMaximumSize(QtCore.QSize(54, 20))
        self.skills_1_misc_mod.setAlignment(QtCore.Qt.AlignCenter)
        self.skills_1_misc_mod.setObjectName("skills_1_misc_mod")
        self.skills_1_attr_mod = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.skills_1_attr_mod.setEnabled(False)
        self.skills_1_attr_mod.setMinimumSize(QtCore.QSize(0, 23))
        self.skills_1_attr_mod.setMaximumSize(QtCore.QSize(54, 20))
        self.skills_1_attr_mod.setAutoFillBackground(False)
        self.skills_1_attr_mod.setAlignment(QtCore.Qt.AlignCenter)
        self.skills_1_attr_mod.setReadOnly(True)
        self.skills_1_attr_mod.setObjectName("skills_1_attr_mod")
        self.skills_1_rank = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.skills_1_rank.setMinimumSize(QtCore.QSize(0, 23))
        self.skills_1_rank.setMaximumSize(QtCore.QSize(54, 20))
        self.skills_1_rank.setAlignment(QtCore.Qt.AlignCenter)
        self.skills_1_rank.setObjectName("skills_1_rank")
        self.skills_1_total = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.skills_1_total.setMinimumSize(QtCore.QSize(0, 23))
        self.skills_1_total.setMaximumSize(QtCore.QSize(54, 20))
        self.skills_1_total.setAlignment(QtCore.Qt.AlignCenter)
        self.skills_1_total.setObjectName("skills_1_total")
        self.skills_1_skill_name = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.skills_1_skill_name.setMinimumSize(QtCore.QSize(0, 23))
        self.skills_1_skill_name.setObjectName("skills_1_skill_name")
        self.skills_rank_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.skills_rank_label.setMaximumSize(QtCore.QSize(54, 20))
        self.skills_rank_label.setAlignment(QtCore.Qt.AlignCenter)
        self.skills_rank_label.setObjectName("skills_rank_label")
        self.skills_attr_mod_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.skills_attr_mod_label.setMaximumSize(QtCore.QSize(54, 20))
        self.skills_attr_mod_label.setAlignment(QtCore.Qt.AlignCenter)
        self.skills_attr_mod_label.setObjectName("skills_attr_mod_label")
        self.skills_misc_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.skills_misc_label.setMaximumSize(QtCore.QSize(54, 20))
        self.skills_misc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.skills_misc_label.setObjectName("skills_misc_label")
        self.skills_1_attr_choice = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        self.skills_1_attr_choice.setMaximumSize(QtCore.QSize(69, 20))
        self.skills_1_attr_choice.setObjectName("skills_1_attr_choice")
        self.skills_1_attr_choice.addItem("")
        self.skills_1_attr_choice.addItem("")
        self.skills_1_attr_choice.addItem("")
        self.skills_1_attr_choice.addItem("")
        self.skills_1_attr_choice.addItem("")
        self.skills_1_attr_choice.addItem("")
        self.skills_skill_name_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.skills_skill_name_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.skills_skill_name_label.setObjectName("skills_skill_name_label")
        self.skills_attr_choice_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.skills_attr_choice_label.setMaximumSize(QtCore.QSize(69, 20))
        self.skills_attr_choice_label.setAlignment(QtCore.Qt.AlignCenter)
        self.skills_attr_choice_label.setObjectName("skills_attr_choice_label")
        self.skills_total_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.skills_total_label.setMaximumSize(QtCore.QSize(54, 20))
        self.skills_total_label.setAlignment(QtCore.Qt.AlignCenter)
        self.skills_total_label.setObjectName("skills_total_label")

        self.SkillsLayout.addWidget(self.skills_description_label, 0, 6, 1, 1)
        self.SkillsLayout.addWidget(self.skills_1_description_button, 1, 6, 1, 1)
        self.SkillsLayout.addWidget(self.skills_1_misc_mod, 1, 5, 1, 1)
        self.SkillsLayout.addWidget(self.skills_1_attr_mod, 1, 3, 1, 1)
        self.SkillsLayout.addWidget(self.skills_1_rank, 1, 4, 1, 1)
        self.SkillsLayout.addWidget(self.skills_1_total, 1, 2, 1, 1)
        self.SkillsLayout.addWidget(self.skills_1_skill_name, 1, 0, 1, 1)
        self.SkillsLayout.addWidget(self.skills_rank_label, 0, 4, 1, 1)
        self.SkillsLayout.addWidget(self.skills_attr_mod_label, 0, 3, 1, 1)
        self.SkillsLayout.addWidget(self.skills_misc_label, 0, 5, 1, 1)
        self.SkillsLayout.addWidget(self.skills_1_attr_choice, 1, 1, 1, 1)
        self.SkillsLayout.addWidget(self.skills_skill_name_label, 0, 0, 1, 1)
        self.SkillsLayout.addWidget(self.skills_attr_choice_label, 0, 1, 1, 1)
        self.SkillsLayout.addWidget(self.skills_total_label, 0, 2, 1, 1)
        self.translate_skills_box()

    def translate_skills_box(self):
        _translate = QtCore.QCoreApplication.translate
        self.SkillsBox.setTitle(_translate("MainWindow", "Skills"))
        self.skills_description_label.setText(_translate("MainWindow", "Description"))
        self.skills_1_description_button.setText(_translate("MainWindow", "DESC"))
        self.skills_1_misc_mod.setText(_translate("MainWindow", "10"))
        self.skills_1_attr_mod.setText(_translate("MainWindow", "10"))
        self.skills_1_rank.setText(_translate("MainWindow", "10"))
        self.skills_1_total.setText(_translate("MainWindow", "10"))
        self.skills_1_skill_name.setText(_translate("MainWindow", "Lorem ipsum"))
        self.skills_rank_label.setText(_translate("MainWindow", "Rank"))
        self.skills_attr_mod_label.setText(_translate("MainWindow", "Attr mod"))
        self.skills_misc_label.setText(_translate("MainWindow", "Misc"))
        self.skills_1_attr_choice.setItemText(0, _translate("MainWindow", "STR"))
        self.skills_1_attr_choice.setItemText(1, _translate("MainWindow", "DEX"))
        self.skills_1_attr_choice.setItemText(2, _translate("MainWindow", "CON"))
        self.skills_1_attr_choice.setItemText(3, _translate("MainWindow", "INT"))
        self.skills_1_attr_choice.setItemText(4, _translate("MainWindow", "WIS"))
        self.skills_1_attr_choice.setItemText(5, _translate("MainWindow", "CHA"))
        self.skills_skill_name_label.setText(_translate("MainWindow", "Skill name"))
        self.skills_attr_choice_label.setText(_translate("MainWindow", "Attr"))
        self.skills_total_label.setText(_translate("MainWindow", "Total"))