APP_NAME_SINGLE = "Single DnD Character Sheet"
APP_NAME_MULTI = "Multi DnD Character Sheet"
ORG_NAME = "DnDCharacterSheet"
MAIN_WINDOW_SIZE = "main_window_size"
MAIN_WINDOW_POSITION = "main_window_position"
