APP_NAME_SINGLE = "Single DnD Character Sheet"
APP_NAME_MULTI = "Multi DnD Character Sheet"
ORG_NAME = "DnDCharacterSheet"
MAIN_WINDOW_SIZE = "main_window_size"
MAIN_WINDOW_POSITION = "main_window_position"
AUTOSAVE_INTERVAL = "autosave_interval"
LAST_OPENED_CHARACTER_FILE = 'last_opened_file'
APP_LANGUAGE = "language"
ASK_ABOUT_LOADING = "ask_about_loading_last"
OPENED_CHARACTERS_COUNT = 'opened_characters_count'
